# Generated by Django 4.0.5 on 2023-04-05 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accInfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedresult',
            name='outlierList',
        ),
        migrations.RemoveField(
            model_name='savedresult',
            name='portfolioList',
        ),
        migrations.RemoveField(
            model_name='savedresult',
            name='portfolioTYpe',
        ),
        migrations.AddField(
            model_name='savedresult',
            name='clusteredStocksSymbols',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='savedresult',
            name='outlierStocksSymbols',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='savedresult',
            name='portfolioTypeOptions',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='savedresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savedResult', to=settings.AUTH_USER_MODEL),
        ),
    ]
