# Generated by Django 4.0.5 on 2023-04-06 00:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accInfo', '0002_remove_savedresult_outlierlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedresult',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
