# Generated by Django 4.0.5 on 2023-04-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accInfo', '0003_savedresult_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedresult',
            name='category',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
