# Generated by Django 4.0.5 on 2023-04-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accInfo', '0004_savedresult_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedresult',
            name='stockTypeOptions',
            field=models.JSONField(default=list),
        ),
    ]
