# Generated by Django 4.0.5 on 2023-04-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accInfo', '0005_savedresult_stocktypeoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedresult',
            name='remarks',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
