# Generated by Django 4.0.5 on 2023-02-12 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ticket', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='financialRatios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetturnover', models.IntegerField()),
                ('quickratio', models.IntegerField()),
                ('debttoequity', models.IntegerField()),
                ('roe', models.IntegerField()),
                ('dividendyield', models.IntegerField()),
                ('pricetoearnings', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financialRatios', to='StockProf_app.stock')),
            ],
        ),
    ]
