# Generated by Django 4.0.5 on 2023-02-12 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockProf_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialratios',
            name='created',
        ),
        migrations.AddField(
            model_name='financialratios',
            name='dataDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
