# Generated by Django 4.0.5 on 2023-02-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockProf_app', '0002_remove_financialratios_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialratios',
            name='ticket',
            field=models.CharField(max_length=20),
        ),
    ]
