# Generated by Django 4.0.5 on 2023-02-13 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StockProf_app', '0003_alter_financialratios_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialratios',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financialRatios', to='StockProf_app.stock'),
        ),
    ]
