# Generated by Django 4.0.5 on 2023-02-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockProf_app', '0004_alter_financialratios_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ticket',
        ),
        migrations.AddField(
            model_name='stock',
            name='Address',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='AssetType',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='CIK',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='Country',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='Currency',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='Exchange',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='Industry',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='Name',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='Sector',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='Symbol',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
