# Generated by Django 4.0.5 on 2023-02-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockProf_app', '0007_remove_financialratios_ticket_alter_stock_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Industry',
            field=models.CharField(max_length=220),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Name',
            field=models.CharField(max_length=220),
        ),
    ]
