# Generated by Django 4.0.5 on 2023-02-13 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StockProf_app', '0008_alter_stock_industry_alter_stock_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialratios',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financialRatios', to='StockProf_app.stock', to_field='Symbol'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Symbol',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
