# Generated by Django 4.0.5 on 2023-02-13 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockProf_app', '0009_financialratios_ticket_alter_stock_symbol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialratios',
            old_name='dataDate',
            new_name='date',
        ),
    ]
