# Generated by Django 4.0.5 on 2023-02-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockProf_app', '0010_rename_datadate_financialratios_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialratios',
            name='date',
            field=models.DateField(),
        ),
    ]
