# Generated by Django 4.0.5 on 2023-02-14 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockProf_app', '0011_alter_financialratios_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialratios',
            old_name='ticket',
            new_name='ticker',
        ),
    ]
