# Generated by Django 4.0.5 on 2023-03-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockProf_app', '0013_alter_financialratios_assetturnover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialratios',
            name='assetturnover',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialratios',
            name='debttoequity',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialratios',
            name='dividendyield',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialratios',
            name='pricetoearnings',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialratios',
            name='quickratio',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialratios',
            name='roe',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='AssetType',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Country',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Currency',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Exchange',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Industry',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='stock',
            name='Name',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
