# Generated by Django 4.0.5 on 2023-03-12 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockProf_app', '0014_alter_financialratios_assetturnover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='AssetType',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='CIK',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='Currency',
        ),
    ]
