# Generated by Django 4.0.5 on 2023-03-25 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StockProf_app', '0015_remove_stock_address_remove_stock_assettype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.CharField(max_length=50, unique=True)),
                ('Name', models.CharField(blank=True, max_length=220)),
                ('Exchange', models.CharField(blank=True, max_length=20)),
                ('Sector', models.CharField(max_length=20)),
                ('Industry', models.CharField(blank=True, max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='financial_ratios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetturnover', models.DecimalField(decimal_places=4, max_digits=10)),
                ('quickratio', models.DecimalField(decimal_places=4, max_digits=10)),
                ('debttoequity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('roe', models.DecimalField(decimal_places=4, max_digits=10)),
                ('dividendyield', models.DecimalField(decimal_places=4, max_digits=10)),
                ('pricetoearnings', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ticker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_ratios', to='StockProf_app.stocks', to_field='Symbol')),
            ],
        ),
    ]
