# Generated by Django 4.0.5 on 2023-03-27 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StockProf_app', '0016_stocks_financial_ratios'),
    ]

    operations = [
        migrations.CreateModel(
            name='MY_financialRatios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetturnover', models.DecimalField(decimal_places=4, max_digits=10)),
                ('quickratio', models.DecimalField(decimal_places=4, max_digits=10)),
                ('debttoequity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('roe', models.DecimalField(decimal_places=4, max_digits=10)),
                ('dividendyield', models.DecimalField(decimal_places=4, max_digits=10)),
                ('pricetoearnings', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MY_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.CharField(max_length=50, unique=True)),
                ('Name', models.CharField(blank=True, max_length=220)),
                ('Category', models.CharField(blank=True, max_length=220)),
            ],
        ),
        migrations.DeleteModel(
            name='financial_ratios',
        ),
        migrations.DeleteModel(
            name='Stocks',
        ),
        migrations.AddField(
            model_name='my_financialratios',
            name='ticker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_ratios', to='StockProf_app.my_stock', to_field='Symbol'),
        ),
    ]
